src/MaCantine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('menu/', include('menu.urls')),
    path('plat/', include('plat.urls')),
]

src/dashboard/urls.py
from django.urls import path
from .views import index

app_name = 'dashboard'

urlpatterns = [
    path('', index, name='index'),
]

src/menu/urls.py
from django.urls import path
from .views import index, add_menu, update_menu, delete_menu

app_name = 'menu'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_menu, name='add_menu'),
    path('update/<int:id>/', update_menu, name='update_menu'),
    path('delete/<int:id>/', delete_menu, name='delete_menu'),
]

src/plat/urls.py
from django.urls import path
from .views import index, add_plat, update_plat, delete_plat

app_name = 'plat'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_plat, name='add_plat'),
    path('update/<int:id>/', update_plat, name='update_plat'),
    path('delete/<int:id>/', delete_plat, name='delete_plat'),
]

src/dashboard/models.py
from django.db import models

# Create your models here.

src/menu/models.py
from django.db import models
from plat.models import Plat

# Create your models here.

class Menu(models.Model):
    plat = models.OneToOneField('plat.Plat', on_delete=models.CASCADE)
    creation_date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f"Menu du {self.creation_date}"
        
class Meta:
    verbose_name = 'Menu'
    verbose_name_plural = 'Menus'

src/plat/models.py
from django.db import models

# Create your models here.
class Plat(models.Model):
    name = models.CharField(max_length=200)
    summary = models.TextField()

    def __str__(self):
        return self.name
        
class Meta:
    verbose_name = 'Plat'
    verbose_name_plural = 'Plats'

src/menu/forms.py
from django import forms
from .models import Menu


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['plat']
        widgets = {
            'plat': forms.Select(attrs={'class': 'form-control'}),
        }

src/plat/forms.py
from django import forms
from .models import Plat




class PlatForm(forms.ModelForm):
    class Meta:
        model = Plat
        fields = ['name', 'summary']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control'}),
        }

src/dashboard/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'dashboard/index.html')

src/menu/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import MenuForm
from .models import Menu

# Create your views here.

def index(request):
    search_field = request.GET.get('search')
    if search_field:
        menus = Menu.objects.filter(plat__icontains=search_field)
        context = {'menus': menus, 'search_field': search_field}
    else:
        menus = Menu.objects.all()
        numbers_menus = menus.count()
        context = {
            'menus': menus,
            'numbers_menus': numbers_menus,
        }
    return render(request, 'menu/menus.html', context)
    
    

def add_menu(request):
    if request.method == 'POST':
        menu_form = MenuForm(request.POST)
        if menu_form.is_valid():
            menu_form.save()
            messages.success(request, 'Menu ajouter avec succès')
            return redirect('menu:index')
        else:
            messages.error(request, 'Erreur lors de l\'ajout du menu')
            return render (request, 'menu/forms.html')
            
    menu_form = MenuForm()
    context = {'form' : menu_form, 'title': 'Ajouter un menu',}
    return render(request, 'menu/forms.html', context)
    
    

def update_menu(request, id):
    menu = Menu.objects.get(id=id)
    
    if request.method == 'POST':
        menu_form = MenuForm(request.POST, instance=menu)
        if menu_form.is_valid():
            menu_form.save()
            messages.success(request, 'menu a bien été modifié')
            return redirect('menu:index')
        else:
            messages.error(request, 'Erreur lors de la modification du menu')
            return render(request, 'menu/forms.html', {'form': menu_form})
            
    menu_form = MenuForm(instance=menu)
    context = {'form': menu_form,
            'title': 'Modification du menu',
        
        }
    return render(request, 'menu/forms.html', context)
        
        

def delete_menu(request, id):
    menu = Menu.objects.get(id=id)
    menu.delete()
    messages.success(request, 'Menu supprimé avec succès')
    return redirect('menu:index')

src/plat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import PlatForm
from .models import Plat

def index(request):
    search_field = request.GET.get('search')
    if search_field:
        plats = Plat.objects.filter(name__icontains=search_field)
        context = {'plats': plats, 'search_field': search_field}
    else:
        plats = Plat.objects.all()
        numbers_plats = plats.count()
        context = {
            'plats': plats,
            'numbers_plats': numbers_plats,
        }
    return render(request, 'plat/plats.html', context)

def add_plat(request):
    if request.method == 'POST':
        plat_form = PlatForm(request.POST)
        if plat_form.is_valid():
            plat_form.save()
            messages.success(request, 'Le plat est ajouté avec succès')
            return redirect('plat:index')
        else:
            messages.error(request, 'Erreur lors de l\'ajout du plat')
            return render(request, 'plat/add_plat.html', {'form': plat_form})
        
    plat_form = PlatForm()
    context = {'form': plat_form, 'title': 'Ajouter un plat'}
    return render(request, 'plat/add_plat.html', context)

def update_plat(request, id):
    plat = get_object_or_404(Plat, id=id)
    
    if request.method == 'POST':
        plat_form = PlatForm(request.POST, instance=plat)
        if plat_form.is_valid():
            plat_form.save()
            messages.success(request, 'Le plat a bien été modifié')
            return redirect('plat:index')
        else:
            messages.error(request, 'Erreur lors de la modification du plat')
            return render(request, 'plat/add_plat.html', {'form': plat_form})
        
    plat_form = PlatForm(instance=plat)
    context = {'form': plat_form, 'title': 'Modification du plat'}
    return render(request, 'plat/add_plat.html', context)

def delete_plat(request, id):
    plat = get_object_or_404(Plat, id=id)
    plat.delete()
    messages.success(request, 'Le plat a été supprimé avec succès')
    return redirect('plat:index')

src/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  {% block title %}
  <title>
    Ma cantine scolaire
  </title>
  {% endblock title %}
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
<link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

<body class="g-sidenav-show  bg-gray-200">
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

  <div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
       aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href="{% url 'dashboard:index' %}"
       target="_blank">
      <img src="{% static 'img/logo-ct.png' %}" class="navbar-brand-img h-100" alt="main_logo">
      <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
    </a>
  </div>


  <hr class="horizontal light mt-0 mb-2">

  <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">


      <li class="nav-item">
        <a class="nav-link text-white " href="{% url 'menu:index' %}">

          <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <span class="material-symbols-outlined">menu_book</span>
          </div>

          <span class="nav-link-text ms-1">Menus</span>
        </a>
      </li>


      <li class="nav-item">
        <a class="nav-link text-white " href="{% url 'plat:index' %}">

          <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <span class="material-symbols-outlined">local_cafe</span>
          </div>

          <span class="nav-link-text ms-1">Plats</span>
        </a>
      </li>

    </ul>
  </div>

</aside>
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    
        {% block content %} 
        
        
        {% endblock content %}
    
      <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
                ADA
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static  'js/material-dashboard.min.js' %}"></script>
</body>

</html>

src/templates/dashboard/index.html
{% extends "base.html" %}


{% load static %}
{% block title %} 

{% endblock title %}




    
        {% block content %}
        
        <div class="flex-1 p-6 fade-in">
      
            {% if messages %}
            <div class="mb-4">
              {% for message in messages %}
                <div class="p-4 mb-2 text-sm {% if message.tags == 'success' %}bg-green-100 text-green-700{% elif message.tags == 'error' %}bg-red-100 text-red-700{% elif message.tags == 'warning' %}bg-yellow-100 text-yellow-700{% endif %} rounded">
                  {{ message }}
                </div>
              {% endfor %}
            </div>
          {% endif %}
          
            <h1 class="text-3xl font-semibold mb-6">Tableau de bord</h1>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <!-- Stat Box 1 -->
              <div class="bg-white p-6 rounded-lg shadow-lg">
                <h3 class="text-lg font-medium text-gray-700 mb-4">Nombre de menus</h3>
                <p class="text-3xl font-bold text-blue-600">{{ numbers_menus }}</p>
              </div>
              <!-- Stat Box 2 -->
              <div class="bg-white p-6 rounded-lg shadow-lg">
                <h3 class="text-lg font-medium text-gray-700 mb-4">Nombre de plats</h3>
                <p class="text-3xl font-bold text-green-600">{{ numbers_plats }}</p>
              </div>
              
              
              </div>
            </div>
          </div>
        </div>
        
        {% endblock content %}

src/templates/menu/forms.html
{% extends "base.html" %}


{% load static %}
{% block title %} 

{% endblock title %}




{% block content %}
    <section>
        <div class="page-header min-vh-100">
        
            <a
            href="{% url 'menu:index' %}"
            class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M15 19l-7-7 7-7"
              />
            </svg>
            Retour
          </a>
                
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">{{title}}</h4>
                            </div>
                            <div class="card-body">
                                <form role="form" method="POST" class="grid grid-cols-2 gap-6">
                                    {% csrf_token %}

                                            {{form}}
                                    <div class="text-center">
                                        <button type="submit"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

src/templates/menu/menus.html
{% extends "base.html" %}


{% load static %}
{% block title %} 

{% endblock title %}

{% block content %}
  
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">
        {% if messages %}
        <div class="mb-4">
          {% for message in messages %}
            <div class="p-4 mb-2 text-sm {% if message.tags == 'success' %}bg-green-100 text-green-700{% elif message.tags == 'error' %}bg-red-100 text-red-700{% elif message.tags == 'warning' %}bg-yellow-100 text-yellow-700{% endif %} rounded">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'menu:add_menu'%}">Ajouter un menu</a>
            </li>
          </ul>
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <label class="form-label">Recherche par nom</label>
              <input type="text" class="form-control" name="search" value="{{search_field}}">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Liste des menus ({{ total }})</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Plat</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"> Actions </th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for menu in menus %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{menu.creation_date}}</h6>
                          </div>
                        </div>
                      </td>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{menu.plat.name}}</h6>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <a href="{% url 'menu:update_menu' menu.id %}" class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded transition duration-300">Modifier</a>
                        <button class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded ml-2 transition duration-300" onclick="openModal({{ menu.id }})">Supprimer</button>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      
      <!-- Modal -->
   <div id="deleteModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden modal-enter">
    <div class="relative top-1/4 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white modal-enter-active">
        <div class="mt-3 text-center">
            <h3 class="text-lg leading-6 font-medium text-gray-900">Confirmer la suppression</h3>
            <div class="mt-2 px-7 py-3">
                <p class="text-sm text-gray-500">Êtes-vous sûr de vouloir supprimer cet élément ? Cette action est irréversible.</p>
            </div>
            <div class="items-center px-4 py-3">
                <button id="confirmDelete" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300" onclick="deleteItem()">Supprimer</button>
                <button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded ml-2 transition duration-300" onclick="closeModal()">Annuler</button>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript -->
<script>
    let menuIdToDelete;

    function openModal(id) {
        menuIdToDelete = id;
        const modal = document.getElementById('deleteModal');
        modal.classList.remove('hidden');
    }

    function closeModal() {
        const modal = document.getElementById('deleteModal');
        modal.classList.add('hidden');
    }

    function deleteItem() {
        window.location.href = `/menu/delete/${menuIdToDelete}/`;
    }
</script>
      
{% endblock content %}

src/templates/plat/add_plat.html
{% extends "base.html" %}


{% load static %}
{% block title %} 

{% endblock title %}




{% block content %}
    <section>
        <div class="page-header min-vh-100">
        
            <a
            href="{% url 'menu:index' %}"
            class="text-gray-500 hover:text-gray-700 flex items-center mb-6"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5 mr-2"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M15 19l-7-7 7-7"
              />
            </svg>
            Retour
          </a>
                
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">{{title}}</h4>
                            </div>
                            <div class="card-body">
                                <form role="form" method="POST" class="grid grid-cols-2 gap-6">
                                    {% csrf_token %}

                                        {{form}}
                                    <div class="text-center">
                                        <button type="submit"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

src/templates/plat/plats.html
{% extends "base.html" %}


{% load static %}
{% block title %} 

{% endblock title %}


{% block content %}
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
  <div class="container-fluid py-1 px-3">
    {% if messages %}
    <div class="mb-4">
      {% for message in messages %}
        <div class="p-4 mb-2 text-sm {% if message.tags == 'success' %}bg-green-100 text-green-700{% elif message.tags == 'error' %}bg-red-100 text-red-700{% elif message.tags == 'warning' %}bg-yellow-100 text-yellow-700{% endif %} rounded">
          {{ message }}
        </div>
      {% endfor %}
    </div>
  {% endif %}
    
    <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
      <ul class="navbar-nav  justify-content-start">
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'plat:add_plat'%}">Ajouter un plat</a>
        </li>
      </ul>
      <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        <div class="input-group input-group-outline">
          <label class="form-label">Recherche par nom</label>
          <input type="text" class="form-control" name="search" value="{{search_field}}">
        </div>
      </div>
      <ul class="navbar-nav  justify-content-end">
        <li class="nav-item d-flex align-items-center">
          <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="container-fluid py-4">
  <div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize ps-3">Liste des plats ({{ total }})</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Libelle</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                </tr>
              </thead>
              <tbody>
                {% for plat in plats %}
                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{ plat.name }}</h6>
                      </div>
                    </div>
                  </td>
                  <td>
                    <div class="d-flex px-2 py-1">
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{ plat.summary }}</h6>
                      </div>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <a href="{% url 'plat:update_plat' plat.id %}" class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-4 rounded transition duration-300">Modifier</a>
                    <button class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-4 rounded ml-2 transition duration-300" onclick="openModal({{ plat.id }})">Supprimer</button>
                  </td>
                </tr>
                {% endfor %}
    </div>
  </div>
  
  
   <!-- Modal -->
   <div id="deleteModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden modal-enter">
    <div class="relative top-1/4 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white modal-enter-active">
        <div class="mt-3 text-center">
            <h3 class="text-lg leading-6 font-medium text-gray-900">Confirmer la suppression</h3>
            <div class="mt-2 px-7 py-3">
                <p class="text-sm text-gray-500">Êtes-vous sûr de vouloir supprimer cet élément ? Cette action est irréversible.</p>
            </div>
            <div class="items-center px-4 py-3">
                <button id="confirmDelete" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300" onclick="deleteItem()">Supprimer</button>
                <button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded ml-2 transition duration-300" onclick="closeModal()">Annuler</button>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript -->
<script>
    let platIdToDelete;

    function openModal(id) {
        platIdToDelete = id;
        const modal = document.getElementById('deleteModal');
        modal.classList.remove('hidden');
    }

    function closeModal() {
        const modal = document.getElementById('deleteModal');
        modal.classList.add('hidden');
    }

    function deleteItem() {
        window.location.href = `/plat/delete/${platIdToDelete}/`;
    }
</script>
  
{% endblock content %}